default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: streaming_replication_example_development

  test:
  <<: *default
  database: streaming_replication_example_test

production:
  <<: *default
  database: streaming_replication_example_production
  username: streaming_replication_example
  password: <%= ENV['STREAMING_REPLICATION_EXAMPLE_DATABASE_PASSWORD'] %>
  url: <%= ENV['RDS_DATABASE_URL'] %>
